services:
  app:
    build: .
    ports:
      - 127.0.0.1:8080:8000
    volumes:
      - ./backend/storage:/app/storage
    env_file:
      - backend/storage/config.env
    command: ["fastapi", "run", "/app/main.py", "--host", "0.0.0.0"]
